# Generated by Django 5.2.11 on 2026-02-16 08:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(help_text='Format: PREFIX-YYYY-NNNN (example: LAB-2026-0001)', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Use sample code format like LAB-2026-0001.', regex='^[A-Z]{2,6}-\\d{4}-\\d{3,6}$')])),
                ('submitter', models.CharField(max_length=120)),
                ('project', models.CharField(max_length=120)),
                ('received_at', models.DateField(default=django.utils.timezone.localdate)),
                ('processed_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', max_length=16)),
                ('qc_score', models.PositiveSmallIntegerField(help_text='QC score between 0 and 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('processed_at__isnull', True), ('processed_at__gte', models.F('received_at')), _connector='OR'), name='processed_after_received'), models.CheckConstraint(condition=models.Q(('qc_score__gte', 0), ('qc_score__lte', 100)), name='qc_score_in_range')],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('visible_columns', models.JSONField(default=list)),
                ('status_filter', models.CharField(blank=True, choices=[('', 'All statuses'), ('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=16)),
                ('min_qc_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ordering', models.CharField(choices=[('-received_at', 'Newest received first'), ('received_at', 'Oldest received first'), ('-qc_score', 'Highest QC first'), ('qc_score', 'Lowest QC first'), ('sample_code', 'Sample code A-Z')], default='-received_at', max_length=32)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_saved_view_name_per_user')],
            },
        ),
    ]
