# Generated by Django 5.2.11 on 2026-03-09 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedTableView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("table_name", models.CharField(max_length=128)),
                ("visible_columns", models.JSONField(default=list)),
                ("ordering", models.CharField(blank=True, max_length=128)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_table_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["table_name", "-is_default", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "table_name", "name"),
                        name="unique_saved_table_view_name_per_user",
                    ),
                ],
            },
        ),
    ]
